name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile main.tex
        uses: dante-ev/latex-action@edge
        with:
          root_file: main.tex
      
      - uses: actions/download-artifact@v3
        with:
          name: main.pdf
    
      - name: Display structure of downloaded files
        run: ls -R
