name: Build  # Name of the GitHub Actions workflow

on: 
  - push  # Trigger the workflow on push events

jobs:
  paper:  # Define a job named "paper"
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu
    container: 
      image: registry.gitlab.com/islandoftex/images/texlive:latest  # Use the specified Docker image
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: .
      FILE: main  # Specify the main latex file

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 100  # Fetch a deep history to enable latexdiff

      - name: Create latex diff file
        shell: bash
        run: |
          # Install necessary dependencies and configure latexdiff
          apt-get -y install perl # Needed for latexdiff
          git clone https://github.com/ftilmann/latexdiff.git /opt/latexdiff 
          git clone https://gitlab.com/git-latexdiff/git-latexdiff /opt/gitlatexdiff
          git config --global --add safe.directory '*'
          
          # Determine OLD and NEW commit hashes for latexdiff
          if [[ $(echo $OLD) ]] ; then OLD=$(git log -n$(echo $OLD) --format="%h" -- *.tex | tail -1) ; else OLD=$(git log -n2 --format="%h" -- *.tex | tail -1); fi
          if [[ $(echo $NEW) ]] ;  then NEW=$(git log -n$(echo $NEW) --format="%h" -- *tex | tail -1); else NEW=$(git log -n1 --format="%h"); fi
          
          # Perform latexdiff and modify diffversion.tex
          mkdir git-latexdiff
          git latexdiff --quiet --no-view --ignore-makefile --main ${{ env.FILE }}.tex --tmpdirprefix ./git-latexdiff/ --cleanup keeppdf $OLD $NEW
          latexdiff $(find . -name "old*.tex" ) $(find . -name "new*.tex") > diffversion.tex
          sed -i 's/\\begin{document}/\\usepackage{draftwatermark} \\SetWatermarkText{LaTex Diff Version of '"$OLD"' to '"$NEW"'} \\SetWatermarkAngle{0} \\SetWatermarkScale{1} \\SetWatermarkVerCenter{.05\\textheight} \\SetWatermarkLightness{0.4} \\begin{document}/' diffversion.tex      
          latexmk -pdf diffversion.tex

      - name: LaTeX compile
        working-directory: ${{ env.DIR }}
        run: latexmk -pdf ${{ env.FILE }}.tex  # Compile the main latex file

      - name: move
        run: |
          mkdir -p github_artifacts && ls && mv ${{ env.DIR }}/diffversion.pdf ./github_artifacts/ && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/ 

      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts

  deploy:
    # Edit here if compiling multiple papers
    needs: [paper]  # Ensure "deploy" job runs after "paper" job
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          path: github_artifacts

      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy

      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true  # Create an orphan branch for deployment
