name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - run: apt-get -y install perl # Needed for latexdiff
      - name: Compile main.tex
        uses: dante-ev/latex-action@edge
        with:
          root_file: main.tex
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: main.pdf
