name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: 
      image: registry.gitlab.com/islandoftex/images/texlive:latest
    steps:    
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - shell: bash
        run: |
         apt-get -y install perl # Needed for latexdiff
         apt-get -y install perl # Needed for latexdiff
         git clone https://github.com/ftilmann/latexdiff.git /opt/latexdiff
         git clone https://gitlab.com/git-latexdiff/git-latexdiff /opt/gitlatexdiff
         (cd /opt/gitlatexdiff && make install-bin)
         git log
         OLD=$(git log -n2 --format="%h" -- *.tex | tail -1)
         NEW=$(git log -n1 --format="%h")
         mkdir git-latexdiff
         git latexdiff --quiet --no-view --ignore-makefile --main main.tex --tmpdirprefix ./git-latexdiff/ --cleanup keeppdf $OLD $NEW
         latexdiff $(find . -name "old*.tex" ) $(find . -name "new*.tex") > diffversion.tex
         sed -i 's/\\begin{document}/\\usepackage{draftwatermark} \\SetWatermarkText{LaTex Diff Version of '"$OLD"' to '"$NEW"'} \\SetWatermarkAngle{0} \\SetWatermarkScale{1} \\SetWatermarkVerCenter{.05\\textheight} \\SetWatermarkLightness{0.4} \\begin{document}/' diffversion.tex      
         latexmk -pdf diffversion.tex
     # - name: 'Upload Artifact'
      #  uses: actions/upload-artifact@v3
       # with:
        #  name: my-artifact
         # path: text.txt    
     
      # - name: 'Upload Artifact'
        #uses: actions/upload-artifact@v3
        #with:
         # name: my-artifact
          #path: diffversion.pdf
