name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      #- uses: supplypike/setup-bin@v1
      - name: Compile main.tex
        uses: dante-ev/latex-action@edge
        with:
          root_file: main.tex
      - run: sudo apt-get -y install perl # Needed for latexdiff
      - run: git clone https://github.com/ftilmann/latexdiff.git /opt/latexdiff
      - run: git clone https://gitlab.com/git-latexdiff/git-latexdiff /opt/gitlatexdiff
      - run: (cd /opt/gitlatexdiff && sudo make install-bin)
      - run: if [[ $(echo $OLD) ]] ; then OLD=$(git log -n$(echo $OLD) --format="%h" -- *.tex | tail -1) ; else OLD=$(git log -n2 --format="%h" -- *.tex | tail -1); fi
      - run: if [[ $(echo $NEW) ]] ;  then NEW=$(git log -n$(echo $NEW) --format="%h" -- *tex | tail -1); else NEW=$(git log -n1 --format="%h"); fi
      - run: mkdir git-latexdiff
      - run: docker run latexdiff --quiet --no-view --ignore-makefile --main main.tex --tmpdirprefix ./git-latexdiff/ --cleanup keeppdf $OLD $NEW
      - run: latexdiff $(find . -name "old*.tex" ) $(find . -name "new*.tex") > diffversion.tex
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: main.pdf
